services:
  outline:
    image: outlinewiki/outline:latest
    container_name: outline
    restart: unless-stopped
    ports:
      - "3002:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
    networks:
      - camuda-infra_default
     env_file:
      - /opt/docker/outline/.env 
volumes:
  postgres-data:
    driver: local
    
networks:
  outline-internal:
    driver: bridge
  camuda-infra_default:
    external: true
